domain: api.vacations.iperka.com
metadata:
  name: vacations-api
  namespace: default
spec:
  replicas: 4
imagePullSecrets: []
spring:
  config:
    activate:
      onProfile: development
  data:
    rest:
      maxPageSize: 100
  datasource:
    url: jdbc:h2:mem:vacations-development
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddlAuto: validate
    properties:
      hibernate:
        dialect:
auth0:
  audience: https://api.iperka.com/vacations/
  domain: https://iperka.eu.auth0.com/
springdoc:
  apiDocs:
    enabled: false
    path: /openapi/v3
  showActuator: false
  swaggerUi:
    enabled: false
    url: /openapi/v3
    oauth2RedirectUrl: /oauth2-redirect.html
management:
  server:
    port: 8081
server:
  servlet:
    contextPath: /
